### ISSUE TITLE
无法赎回质押投票

### ISSUE THREAD

**Issue by rickycoder** [starcoinorg/starcoin-poll#46]
钱包地址:0xadaae29a440b4559a4dbb70420622ad5
投票:https://poll.starcoin.org/polls/detail/9?network=main
显示 Not vote yet ,其实有投票, 目前无法赎回解除质押

**Comment by tarvos21** [comment]
@rickycoder 

Please click the connect wallet button in the Poll Detail card again, then the revoke and vote button will appear.

<img width="814" alt="截屏2021-12-30 下午3 12 38" src="https://user-images.githubusercontent.com/18745870/147729736-3430a4c2-a4f3-475e-a86a-b1dc99cb7b45.png">

<img width="424" alt="截屏2021-12-30 下午3 14 30" src="https://user-images.githubusercontent.com/18745870/147729782-dfc5188f-a86a-4c13-b543-c8699e386ce8.png">

**Comment by rickycoder** [comment]
clean chrome cache
reconnect wallet

no vote and revoke button  

![image](https://user-images.githubusercontent.com/1294484/147735786-42e3bdb3-d45c-47d3-9a86-90e68294f174.png)

**Comment by wk3368** [comment]
fixed in v1.12.2
